### ISSUE TITLE
BottomSheet sheet-heights not assigned

### ISSUE THREAD

**Issue by elFallino** [shishirraven/bravevue#6]
It seems that the parameters for the BottomSheet-heights in its different states are not applied when using the parameters suggested in the examples (_sheet-close, sheet-half-open, sheet-full-open_).

When using the parameter names that can be found in the bravevue.es.js (_closeHeight, halfHeight, fullHeight_) it seems to work.

I guess the example just does not match the correct parameter names.

Thank you for your great work.

**Comment by shishirraven** [comment]
Hi @elFallino,
Thanks for letting me know this. 
I will update the documentation ASAP and let you know in comments again.

**Comment by shishirraven** [comment]
HI @elFallino 

I have updated the documentation with the right props in the Example. 
https://braveui.com/brave-bottom-sheet#props
