### ISSUE TITLE
BottomSheet: Add a parameter to disable half-transparent dark background

### ISSUE THREAD

**Issue by elFallino** [shishirraven/bravevue#7]
In some cases it might not be wished that there is an extra layer that darkens the layers behind the BottomSheet (that one that adds a black background with 50% opacity).

Please add a parameter to disable this behavior.

Thank you very much.

**Comment by shishirraven** [comment]
Hello @elFallino, 

Based on your suggestion I have added new props to control the opacity. 
backDropOpacity

this can be set to 0 to now show the black background.  as follows. 
`  backDropOpacity="0%"`

additionally I have added more properties you can control like. 
backDropColor - Change the color of backdrop
backdropZIndex - Change Z-index of Backdrop
zIndex - Change Z-index of the bottomsheet

You can find more on the documentation page 
https://braveui.com/brave-bottom-sheet#props

Thankyou
Shishir

**Comment by elFallino** [comment]
Great - thank you very much.
